### ISSUE TITLE
Do you have  RDN models on the pytorch framework?

### ISSUE THREAD

**Issue by Zysty** [yulunzhang/RDN#17]
Hi,
I cannot install Torch7 because it is too old to install corresponding software  package.
So do you have  RDN models on the pytorch framework?
Or could you share some SR results produced by RDN?
I just want to compare visual quality.
Looking forward to your reply

**Comment by Zysty** [comment]
I have retrained the model by pytorch version.

**Comment by dragonblood** [comment]
can you share the link?
