### ISSUE TITLE
denseblock有没有用Bottleneck layers设计

### ISSUE THREAD

**Issue by IPNUISTlegal** [yulunzhang/RDN#6]
您好，本人没有学过lua语言，尽力去看懂您的代码，但还是不能理解。最初densenet在3*3之前加了一层1*1（减少输入特征图的数量，从而提高计算效率），看您论文当中并没有类似的操作，不知道您的代码或者实现中，是不是没有Bottleneck layers设计？非常抱歉用中文向您提问，感谢

**Comment by yulunzhang** [comment]
您好，
代码实现的网络结构和论文中图2，3一致。里面没有和原始densenet那样的bottleneck（连接bock与block）。当然，每个RDB中最后一个1x1的卷积层就是来减少特征数的。

**Comment by IPNUISTlegal** [comment]
感谢
