### ISSUE TITLE
Could you please provide the result image of the degradation model?

### ISSUE THREAD

**Issue by wxywhu** [yulunzhang/RDN#8]
Hi, thank you so much for the source code. Besides, could you please provide the resulting image of the degradation model? I am not familiar with torch.  I test the tensorflow version and find it do not reach the best performance.

**Comment by yulunzhang** [comment]
Hi,
What do you mean 'resulting image of the degradation model'? The super-resolved results for BI/BD/DN degradation models? If so, you can find them from 
https://pan.baidu.com/s/1jKmu14y?errno=0&errmsg=Auth%20Login%20Sucess&&bduss=&ssnerror=0&traceid=
